"""Added public_id UUID

Revision ID: 634b85b36482
Revises: 6fc230652fd9
Create Date: 2026-03-30 11:45:29.376900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634b85b36482'
down_revision = '6fc230652fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
